### ISSUE TITLE
still works?

### ISSUE THREAD

**Issue by raihan2727** [xcqLL/Vanguard-Valorant-Bypass#2]
is this still working? if yes, how i do it with 2 pc?

**Comment by xcqLL** [comment]
km harus mattin vgk vgc pake vanguard bypass itu  ters ke pc 1 (yang buat cheat) dan ke pc 2 (yang buat login awal)
terus lu habis mattin vgc/vgk di pc 1 yang buat cheat lu buka pc ke 2 trs login valorant , nah pas di lobby , lu ke pc 1 lu tabrak + buka pake cheat , trs kalo udah di pc 2 otomatis nnti ada peringatan kalo ada yang nabrak akun nya , kalo udah di pc 1 lu langsung cari match cpt dan 2 menit / 1 menit hrs udh masuk ke game , nah di pc 2 jangan di tekan exit tapi di biarin aja (pas kena error itu kan ada button quit jangan di tekan , tapi di biarin)

ini vanguard bypass jadi buat ngurangi resiko banned kalo buat nge cit dan kalo elu ke ban pas 1 match lu mainnya kurang bersih atau emang driver cheat nya yang ke detected

**Comment by raihan2727** [comment]
di PC 1 nya tar kaga bakalan kena van 83 atau eror lain pas login?

**Comment by xcqLL** [comment]
kaga , kan lu nabrak nya pake pc yang ke 2

**Comment by raihan2727** [comment]
oke paham, gw coba tutor nya. soalnya kemaren² pake 1 pc sebelum kena patch ini method. thx tutornya

**Comment by xcqLL** [comment]
aman

**Comment by xcqLL** [comment]
soalnya ada yang jual sampe 2 /3 juta , bypass 2 pc 😂 dan satu lagi Fungsi VGC bypass adalah untuk mengurangi resiko ban.

**Comment by raihan2727** [comment]
ahahaha, P2C tai wkwk.

**Comment by xcqLL** [comment]
ini itu sebenernya gratis, tapi ada yang jual

**Comment by xcqLL** [comment]
ini ku close , ty ty
